### ISSUE TITLE
All status.addresses show up as ExternalIP

### ISSUE THREAD

**Issue by Waizzzzz** [spectrocloud/cluster-api-provider-maas#174]
Hello, I've been trying to use your MaaS provider and I've ran into an issue where every single IP that this provider gets from MaaS is labelled as "ExternalIP" which breaks the functionality of KubeAdm and RKE2 for when it needs to register nodes and I assume this for loop is at fault https://github.com/spectrocloud/cluster-api-provider-maas/blob/6ec0c47f173da23fe1b4935a7823013a9eb0ff15/pkg/maas/machine/machine.go#L157

We are currently on `v0.6.1` version of the provider

And I was wondering if there is a way to force the labelling to be InternalIP instead of ExternalIP or is this a bug with the provider?

(the IPs and DNS are obviously not the real ones)

```
status:
  addresses:
    - address: _server-name.maas_
      type: ExternalDNS
    - address: 10.2.0.2
      type: ExternalIP
    - address: 151.123.200.120
      type: ExternalIP
    - address: 151.123.200.128
      type: ExternalIP
```
